// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using challengeFiap.Infrastruture.Data;

#nullable disable

namespace ChallengeFiap.Infrastruture.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("challengeFiap.Domain.Entities.Animal", b =>
                {
                    b.Property<int>("Id_animal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_animal");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_animal"));

                    b.Property<DateTime>("Dt_nascimento_animal")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_nascimento_animal");

                    b.Property<string>("Especie_animal")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("especie_animal");

                    b.Property<int>("Id_tutor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_tutor");

                    b.Property<string>("Nm_animal")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_animal");

                    b.Property<string>("Nr_microchip_animal")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nr_microchip_animal");

                    b.Property<decimal>("Peso_animal")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("peso_animal");

                    b.Property<string>("Raca_animal")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("raca_animal");

                    b.Property<string>("Rg_animal")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("rg_animal");

                    b.HasKey("Id_animal");

                    b.HasIndex("Id_tutor");

                    b.ToTable("T_CLYVO_ANIMAL", (string)null);
                });

            modelBuilder.Entity("challengeFiap.Domain.Entities.CarteiraVacinal", b =>
                {
                    b.Property<int>("Id_carteiraVacinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_carteiravacinal");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_carteiraVacinal"));

                    b.Property<DateTime>("Dt_vacina_efetuada")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_vacinacao_efetuada");

                    b.Property<DateTime>("Dt_vacina_prevista")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_vacinacao_prevista");

                    b.Property<int>("Id_animal")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_animal");

                    b.Property<string>("Nm_vacina")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_vacina");

                    b.Property<int>("St_vacina")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("st_vacinacao");

                    b.HasKey("Id_carteiraVacinal");

                    b.HasIndex("Id_animal");

                    b.ToTable("T_CLYVO_CARTEIRAVACINAL", (string)null);
                });

            modelBuilder.Entity("challengeFiap.Domain.Entities.Clinica", b =>
                {
                    b.Property<int>("Id_clinica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_clinica");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_clinica"));

                    b.Property<string>("Cnpj_clinica")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cnpj_clinica");

                    b.Property<string>("Nm_clinica")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_clinica");

                    b.HasKey("Id_clinica");

                    b.ToTable("T_CLYVO_CLINICA", (string)null);
                });

            modelBuilder.Entity("challengeFiap.Domain.Entities.Consulta", b =>
                {
                    b.Property<int>("Id_consulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_consulta");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_consulta"));

                    b.Property<DateTime>("Dt_consulta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_consulta");

                    b.Property<string>("Historico_consulta")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("historico_consulta");

                    b.Property<int>("Id_animal")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_animal");

                    b.Property<int>("Id_vet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_vet");

                    b.Property<int>("St_consulta")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("st_consulta");

                    b.HasKey("Id_consulta");

                    b.HasIndex("Id_animal");

                    b.HasIndex("Id_vet");

                    b.ToTable("T_CLYVO_CONSULTA", (string)null);
                });

            modelBuilder.Entity("challengeFiap.Domain.Entities.EnderecoAnimal", b =>
                {
                    b.Property<int>("Id_endereco_animal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_endereco_animal");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_endereco_animal"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("complemento");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("estado");

                    b.Property<int>("Id_animal")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_animal");

                    b.Property<string>("Logradouro_rua")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("logradouro_rua");

                    b.Property<string>("Nr_rua")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nr_rua");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("pais");

                    b.HasKey("Id_endereco_animal");

                    b.HasIndex("Id_animal")
                        .IsUnique();

                    b.ToTable("T_CLYVO_ENDERECO_ANIMAL", (string)null);
                });

            modelBuilder.Entity("challengeFiap.Domain.Entities.EnderecoClinica", b =>
                {
                    b.Property<int>("Id_endereco_clinica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_endereco_clinica");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_endereco_clinica"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("complemento");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("estado");

                    b.Property<int>("Id_clinica")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_clinica");

                    b.Property<string>("Logradouro_rua")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("logradouro_rua");

                    b.Property<string>("Nr_rua")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nr_rua");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("pais");

                    b.HasKey("Id_endereco_clinica");

                    b.HasIndex("Id_clinica")
                        .IsUnique();

                    b.ToTable("T_CLYVO_ENDERECO_CLINICA", (string)null);
                });

            modelBuilder.Entity("challengeFiap.Domain.Entities.EnderecoTutor", b =>
                {
                    b.Property<int>("Id_endereco_tutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_endereco_tutor");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_endereco_tutor"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("complemento");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("estado");

                    b.Property<int>("Id_tutor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_tutor");

                    b.Property<string>("Logradouro_rua")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("logradouro_rua");

                    b.Property<string>("Nr_rua")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nr_rua");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("pais");

                    b.HasKey("Id_endereco_tutor");

                    b.HasIndex("Id_tutor")
                        .IsUnique();

                    b.ToTable("T_CLYVO_ENDERECO_TUTOR", (string)null);
                });

            modelBuilder.Entity("challengeFiap.Domain.Entities.Medicamento", b =>
                {
                    b.Property<int>("Id_medicamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_medicamento");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_medicamento"));

                    b.Property<string>("Dosagem_medicamento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("dosagem_medicamento");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("frequencia");

                    b.Property<int>("Id_prescricao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_prescricao");

                    b.Property<string>("Nm_medicamento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_medicamento");

                    b.Property<int>("Qtd_dias")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("qtd_dias");

                    b.HasKey("Id_medicamento");

                    b.HasIndex("Id_prescricao");

                    b.ToTable("T_CLYVO_MEDICAMENTO", (string)null);
                });

            modelBuilder.Entity("challengeFiap.Domain.Entities.Prescricao", b =>
                {
                    b.Property<int>("Id_prescricao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_prescricao");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_prescricao"));

                    b.Property<DateTime>("Dt_emissao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_emissao");

                    b.Property<DateTime>("Dt_expiracao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_expiracao");

                    b.Property<int>("Id_consulta")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_consulta");

                    b.Property<string>("Observacoes_gerais")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("observacoes_gerais");

                    b.HasKey("Id_prescricao");

                    b.HasIndex("Id_consulta")
                        .IsUnique();

                    b.ToTable("T_CLYVO_PRESCRICAO", (string)null);
                });

            modelBuilder.Entity("challengeFiap.Domain.Entities.Tutor", b =>
                {
                    b.Property<int>("Id_tutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_tutor");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_tutor"));

                    b.Property<string>("Cpf_tutor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("cpf_tutor");

                    b.Property<string>("Nm_tutor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_tutor");

                    b.Property<string>("Nr_telefone_tutor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nr_telefone_tutor");

                    b.HasKey("Id_tutor");

                    b.HasIndex("Cpf_tutor")
                        .IsUnique()
                        .HasDatabaseName("cpf_tutor");

                    b.ToTable("T_CLYVO_TUTOR", (string)null);
                });

            modelBuilder.Entity("challengeFiap.Domain.Entities.VetClinica", b =>
                {
                    b.Property<int>("Id_clinica_vet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_clinica_vet");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_clinica_vet"));

                    b.Property<int>("Id_clinica")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_clinica");

                    b.Property<int>("Id_vet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_vet");

                    b.HasKey("Id_clinica_vet");

                    b.HasIndex("Id_clinica");

                    b.HasIndex("Id_vet");

                    b.ToTable("T_CLYVO_VET_CLINICA", (string)null);
                });

            modelBuilder.Entity("challengeFiap.Domain.Entities.Veterinario", b =>
                {
                    b.Property<int>("Id_vet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_vet");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_vet"));

                    b.Property<string>("Cpf_vet")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("cpf_vet");

                    b.Property<string>("Crmv_vet")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("crmv_vet");

                    b.Property<string>("Email_vet")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("email");

                    b.Property<string>("Nm_vet")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nm_vet");

                    b.Property<string>("Senha_vet")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("senha");

                    b.HasKey("Id_vet");

                    b.HasIndex("Cpf_vet")
                        .IsUnique()
                        .HasDatabaseName("cpf_vet");

                    b.HasIndex("Crmv_vet")
                        .IsUnique()
                        .HasDatabaseName("crmv_vet");

                    b.ToTable("T_CLYVO_VET", (string)null);
                });

            modelBuilder.Entity("challengeFiap.Domain.Entities.Animal", b =>
                {
                    b.HasOne("challengeFiap.Domain.Entities.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("Id_tutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("challengeFiap.Domain.Entities.CarteiraVacinal", b =>
                {
                    b.HasOne("challengeFiap.Domain.Entities.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("Id_animal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("challengeFiap.Domain.Entities.Consulta", b =>
                {
                    b.HasOne("challengeFiap.Domain.Entities.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("Id_animal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("challengeFiap.Domain.Entities.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("Id_vet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("challengeFiap.Domain.Entities.EnderecoAnimal", b =>
                {
                    b.HasOne("challengeFiap.Domain.Entities.Animal", "Animal")
                        .WithOne()
                        .HasForeignKey("challengeFiap.Domain.Entities.EnderecoAnimal", "Id_animal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("challengeFiap.Domain.Entities.EnderecoClinica", b =>
                {
                    b.HasOne("challengeFiap.Domain.Entities.Clinica", "Clinica")
                        .WithOne()
                        .HasForeignKey("challengeFiap.Domain.Entities.EnderecoClinica", "Id_clinica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("challengeFiap.Domain.Entities.EnderecoTutor", b =>
                {
                    b.HasOne("challengeFiap.Domain.Entities.Tutor", "Tutor")
                        .WithOne()
                        .HasForeignKey("challengeFiap.Domain.Entities.EnderecoTutor", "Id_tutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("challengeFiap.Domain.Entities.Medicamento", b =>
                {
                    b.HasOne("challengeFiap.Domain.Entities.Prescricao", "Prescricao")
                        .WithMany()
                        .HasForeignKey("Id_prescricao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescricao");
                });

            modelBuilder.Entity("challengeFiap.Domain.Entities.Prescricao", b =>
                {
                    b.HasOne("challengeFiap.Domain.Entities.Consulta", "Consulta")
                        .WithOne()
                        .HasForeignKey("challengeFiap.Domain.Entities.Prescricao", "Id_consulta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("challengeFiap.Domain.Entities.VetClinica", b =>
                {
                    b.HasOne("challengeFiap.Domain.Entities.Clinica", "Clinica")
                        .WithMany()
                        .HasForeignKey("Id_clinica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("challengeFiap.Domain.Entities.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("Id_vet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Veterinario");
                });
#pragma warning restore 612, 618
        }
    }
}
